server:
  port: ${REST_SERVICE_PORT:8086}
spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    generate-ddl: true

salt: ${SALT:test}
